// Export image assets here, e.g.:
// export { default as ExampleImage } from './example.png';
export const images = {
  onboardingImage1: require('./OnboardingImage1.png'),
  onboardingImage2: require('./OnboardingImage2.png'),
  onboardingImage3: require('./OnboardingImage3.png'),
  AuthMain: require('./AuthMain.png'),
  LuxuryCarImage: require('./LuxuryCarImage.png'),
  SedanImage: require('./SedanImage.png'),
  SportsCarImage: require('./SportsCarImage.png'),
  VanImage: require('./VanImage.png'),
  WaxGlowImage: require('./WaxGlowImage.png'),
  CarWashImage: require('./CarWashImage.png'),
  CeramicPaintImage: require('./CeramicPaintImage.png'),
  CarImage: require('./CarImage.png'),
  RocketIcon: require('./RocketIcon.png'),
  SilverIcon: require('./SilverIcon.png'),
  CrownIcon: require('./CrownIcon.png'),
  DaimondIcon: require('./DaimondIcon.png'),
  Upcoming: require('./Upcoming.png'),
  TotalServices: require('./TotalServices.png'),
  Gold: require('./Gold.png'),
  DriverDashboardMain: require('./DriverDashboardMain.png'),
  TempProfile: require('./TempProfile.png'),
  AppIcon: require('./AppIcon.png'),
} as const;